optimized_mpc_controller:
  ros__parameters:
    control_hz: 30.0
    cost_function_weights:
      acceleration_weight: 2.0
      heading_weight: 2.0
      jerk_weight: 1.0
      position_weight: 10.0
      steering_weight: 3.0
      velocity_weight: 3.0
    horizon_N: 15
    horizon_T: 1.0
    max_acceleration: 3.0
    max_deceleration: 3.0
    max_speed: 12.0
    max_steering_angle: 0.5
    mpc_type: dynamic
    solver_type: sqpmethod
